version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: volleyball_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend

volumes:
  postgres_data:
